# hello world
GET http://localhost:8080/{{name}}

<> 2024-11-07T140145.200.txt

###
# /v1/authentication
POST http://localhost:8080/v1/authentication
Content-Type: application/json


###
GET http://localhost:8080/rest/6/sub/2

###
GET http://localhost:8080/rest/1/second/2

###
GET http://localhost:8080/uri/21

###
POST http://10.0.63.57:8080/myservice/oauth2/token
Content-Type: application/json

{
  "user": "huangsy",
  "password": "123456",
  "expirationDays": 30
}